SELECT ' ' as LOG_COLUMN,  MVKE.MATNR, MVKE.VKORG 
    , DECODE(MVKE.VRKME,MVKE4000.VRKME,'/',MVKE.VRKME) AS VRKME
    , CASE
        WHEN MVKE.VMSTA <> MVKE4000.VMSTA AND MVKE.DWERK = MVKE4000.DWERK AND MVKE.VKORG <> '4025'
            THEN MVKE.VMSTA
        WHEN MVKE.VMSTA <> MVKE4000.VMSTA AND MVKE.DWERK = MVKE4000.DWERK AND MVKE.VKORG = '4025'  AND MVKE4000.VMSTA IN ('Z8','ZE','ZK','ZJ')
            THEN MVKE.VMSTA
        ELSE '/'
      END AS VMSTA
    --OLD WAY OF CHECKING PRIOR TO 4025 BEING PART OF EMEA            
    --, DECODE(MVKE.VMSTA,MVKE4000.VMSTA,'/',MVKE.VMSTA) AS VMSTA
    , CASE
        WHEN MVKE.VMSTA <> MVKE4000.VMSTA AND MVKE.DWERK = MVKE4000.DWERK AND MVKE.VKORG <> '4025'
            THEN DECODE ( DECODE(MVKE.VMSTD,MVKE4000.VMSTD,'/',MVKE.VMSTD)  ,'/','/','00000000',' ', TO_CHAR ( TO_DATE(  DECODE(MVKE.VMSTD,MVKE4000.VMSTD,'/',MVKE.VMSTD) , 'YYYYMMDD' ) , 'MM/DD/YYYY' )  )
        WHEN MVKE.VMSTA <> MVKE4000.VMSTA AND MVKE.DWERK = MVKE4000.DWERK AND MVKE.VKORG = '4025'  AND MVKE4000.VMSTA IN ('Z8','ZE','ZK','ZJ')
            THEN DECODE ( DECODE(MVKE.VMSTD,MVKE4000.VMSTD,'/',MVKE.VMSTD)  ,'/','/','00000000',' ', TO_CHAR ( TO_DATE(  DECODE(MVKE.VMSTD,MVKE4000.VMSTD,'/',MVKE.VMSTD) , 'YYYYMMDD' ) , 'MM/DD/YYYY' )  )
        ELSE '/'  
      END AS VMSTD 
    --OLD WAY OF CHECKING PRIOR TO 4025 BEING PART OF EMEA          
    --, DECODE(MVKE.VMSTA,MVKE4000.VMSTA,'/', DECODE ( DECODE(MVKE.VMSTD,MVKE4000.VMSTD,'/',MVKE.VMSTD)  ,'/','/','00000000',' ', TO_CHAR ( TO_DATE(  DECODE(MVKE.VMSTD,MVKE.VMSTD,'/',MVKE4000.VMSTD) , 'YYYYMMDD' ) , 'MM/DD/YYYY' )  ) )AS VMSTD
    , CASE
        WHEN MVKE.VKORG = '4025'
            THEN '/'
        WHEN MVKE.DWERK <> MVKE4000.DWERK 
            THEN MVKE4000.DWERK
        ELSE '/'
      END AS DWERK
    --OLD WAY OF CHECKING PRIOR TO 4025 BEING PART OF EMEA     
    --, DECODE(MVKE.DWERK,MVKE4000.DWERK,'/',MVKE4000.DWERK) AS DWERK
    , DECODE(MVKE.SKTOF,MVKE4000.SKTOF,'/',MVKE.SKTOF) AS SKTOF
    , DECODE(MVKE.AUMNG,MVKE4000.AUMNG,'/',MVKE.AUMNG) AS AUMNG
    , DECODE(MVKE.LFMNG,MVKE4000.LFMNG,'/',MVKE.LFMNG) AS LFMNG
    , DECODE(MVKE.SCMNG,MVKE4000.SCMNG,'/',MVKE.SCMNG) AS SCMNG
    , DECODE(MVKE.SCHME,MVKE4000.SCHME,'/',MVKE.SCHME) AS SCHME
    , DECODE(MVKE.RDPRF,MVKE4000.RDPRF,'/',MVKE.RDPRF) AS RDPRF
    , DECODE(MVKE.ZZMAXAU,MVKE4000.ZZMAXAU,'/',MVKE.ZZMAXAU) AS ZZMAXAU
    , DECODE(MVKE.ZZUOQ,MVKE4000.ZZUOQ,'/',MVKE.ZZUOQ) AS ZZUOQ
    , DECODE(MVKE.VERSG,MVKE4000.VERSG,'/',MVKE.VERSG) AS VERSG
    , DECODE(MVKE.KTGRM,MVKE4000.KTGRM,'/',MVKE.KTGRM) AS KTGRM
    , DECODE(MVKE.MTPOS,MVKE4000.MTPOS,'/',MVKE.MTPOS) AS MTPOS
    , DECODE(MVKE.PMATN,MVKE4000.PMATN,'/',MVKE.PMATN) AS PMATN
    , DECODE(MVKE.PROVG,MVKE4000.PROVG,'/',MVKE.PROVG) AS PROVG
    , DECODE(MVKE.MVGR1,MVKE4000.MVGR1,'/',MVKE.MVGR1) AS MVGR1
    , DECODE(MVKE.MVGR2,MVKE4000.MVGR2,'/',MVKE.MVGR2) AS MVGR2
    --MVGR4 SHOULD ONLY BE UPDATED BY THE PRICING TEAM
    --, DECODE(MVKE.MVGR4,MVKE4000.MVGR4,'/',MVKE.MVGR4) AS MVGR4
    , '/' AS MVGR4
    --PRAT1 IS MONITORED BY ANOTHER WEEKLY UPDATE FOR EMEA AND SHOULD NOT BE UPDATED HERE
    --, DECODE(MVKE.PRAT1,MVKE4000.PRAT1,'/',MVKE.PRAT1) AS PRAT1
    , '/' AS PRAT1
    --PRAT2 IS MONITORED BY ANOTHER WEEKLY UPDATE FOR EMEA AND SHOULD NOT BE UPDATED HERE
    --, DECODE(MVKE.PRAT2,MVKE4000.PRAT2,'/',MVKE.PRAT2) AS PRAT2
    , '/' AS PRAT2
    , DECODE(MVKE.PRAT3,MVKE4000.PRAT3,'/',MVKE.PRAT3) AS PRAT3
    , DECODE(MVKE.PRAT4,MVKE4000.PRAT4,'/',MVKE.PRAT4) AS PRAT4
    --PRAT5 IS MONITORED BY ANOTHER WEEKLY UPDATE FOR EMEA AND SHOULD NOT BE UPDATED HERE
    --, DECODE(MVKE.PRAT5,MVKE4000.PRAT5,'/',MVKE.PRAT5) AS PRAT5
    , '/' AS PRAT5
    --PRAT6 IS MONITORED BY ANOTHER WEEKLY UPDATE FOR EMEA AND SHOULD NOT BE UPDATED HERE
    --, DECODE(MVKE.PRAT6,MVKE4000.PRAT6,'/',MVKE.PRAT6) AS PRAT6
    , '/' AS PRAT6
    , DECODE(MVKE.PRAT7,MVKE4000.PRAT7,'/',MVKE.PRAT7) AS PRAT7
    , DECODE(MVKE.PRAT8,MVKE4000.PRAT8,'/',MVKE.PRAT8) AS PRAT8
    , DECODE(MVKE.PRAT9,MVKE4000.PRAT9,'/',MVKE.PRAT9) AS PRAT9    
    --PRATA IS MONITORED BY ANOTHER WEEKLY UPDATE FOR EMEA AND SHOULD NOT BE UPDATED HERE
    --, DECODE(MVKE.PRATA,MVKE4000.PRATA,'/',MVKE.PRATA) AS PRATA
    , '/' AS PRATA
    , DECODE ( DECODE(MVKE.ZZABSDT,MVKE4000.ZZABSDT,'/',MVKE.ZZABSDT)  ,'/','/','00000000',' ', TO_CHAR ( TO_DATE(  DECODE(MVKE.ZZABSDT,MVKE4000.ZZABSDT,'/',MVKE.ZZABSDT) , 'YYYYMMDD' ) , 'MM/DD/YYYY' )  ) AS ZZABSDT
    , DECODE(MVKE.ZZPFRPD,MVKE4000.ZZPFRPD,'/',MVKE.ZZPFRPD) AS ZZPFRPD
    , DECODE(MVKE.ZZWEERG,MVKE4000.ZZWEERG,'/',MVKE.ZZWEERG) AS ZZWEERG
    , DECODE ( DECODE(MVKE.ZZSLRDT,MVKE4000.ZZSLRDT,'/',MVKE.ZZSLRDT)  ,'/','/','00000000',' ', TO_CHAR ( TO_DATE(  DECODE(MVKE.ZZSLRDT,MVKE4000.ZZSLRDT,'/',MVKE.ZZSLRDT) , 'YYYYMMDD' ) , 'MM/DD/YYYY' )  ) AS ZZSLRDT
FROM WINSHUTTLE_LIBRARIAN.WS_REGION_TO_SLS_ORG RSO
        ,SAPECC_DLY_LIBRARIAN.MVKE MVKE4000
        ,SAPECC_DLY_LIBRARIAN.MVKE
        ,SAPECC_DLY_LIBRARIAN.MARA
WHERE MVKE.MATNR = MARA.MATNR
    AND (MARA.MTART IN ('ZFG','ZTG') OR (MARA.MTART = 'ZNFG' AND MARA.MTPOS_MARA LIKE 'ZRS%'))
    --AND MARA.MTART IN ('ZFG','ZTG','ZNFG','ZREP')
    AND RSO.REGION = '4'
    AND MVKE.VKORG = RSO.SALES_ORG
    AND MVKE.VKORG != '4000'
    AND MVKE4000.VKORG = '4000'
    AND MVKE.MANDT = '400'
    AND MVKE4000.MANDT = '400'
    AND MVKE.MATNR = MVKE4000.MATNR
   -- AND MVKE.VKORG = '4004'
    AND MVKE4000.VMSTA NOT IN ( 'NA' , 'Z7')
    AND MVKE4000.DWERK <> '4080'
    AND (MVKE.VMSTA NOT IN ( 'NA' , 'Z7' , 'Z5','ZX') OR (MVKE.VMSTA = 'Z7' AND MARA.SATNR <> ' ' 
                AND (SELECT KONP.KBETR
                  FROM sapecc_dly_librarian.A304,
                       sapecc_dly_librarian.KONP
                 WHERE     A304.MANDT = '400'
                       AND A304.MANDT = KONP.MANDT
                       AND A304.MATNR = MVKE.MATNR
                       AND A304.VKORG = MVKE.VKORG
                       AND A304.KNUMH = KONP.KNUMH
                       AND TO_DATE (A304.DATBI, 'YYYYMMDD') > SYSDATE
                       AND TO_DATE (A304.DATAB, 'YYYYMMDD') < SYSDATE
                       AND KONP.KSCHL = 'ZP00') IS NOT NULL
                  AND (SELECT COUNT(*) AS CNT --HAS AT LEAST 2 EMEA SALES ORGS AT A BLANK D-CHAIN STATUS
                        FROM SAPECC_DLY_LIBRARIAN.MVKE MVKE2
                        WHERE MVKE2.VMSTA = ' '
                            AND MVKE2.MATNR = MVKE.MATNR
                            AND MVKE2.VKORG IN (SELECT RSO1.SALES_ORG FROM WINSHUTTLE_LIBRARIAN.WS_REGION_TO_SLS_ORG RSO1 WHERE RSO1.REGION = '4')
                            AND MVKE2.MANDT = '400') > 1 
                            ))
    AND MVKE.DWERK <> '4080'
    and mvke.matnr <> 'PN-C40712'
    AND (MVKE.VRKME != MVKE4000.VRKME 
       OR (MVKE.VMSTA != MVKE4000.VMSTA AND MVKE.DWERK = MVKE4000.DWERK AND (MVKE.VKORG <> '4025' OR ( MVKE.VKORG = '4025' AND MVKE4000.VMSTA IN ('Z8','ZE','ZK','ZJ'))))
       OR (MVKE.VMSTD != MVKE4000.VMSTD AND MVKE.VMSTA != MVKE4000.VMSTA AND MVKE.DWERK = MVKE4000.DWERK AND (MVKE.VKORG <> '4025' OR ( MVKE.VKORG = '4025' AND MVKE4000.VMSTA IN ('Z8','ZE','ZK','ZJ'))))
       OR (MVKE.DWERK != MVKE4000.DWERK AND MVKE.VKORG <> '4025')
       OR MVKE.SKTOF != MVKE4000.SKTOF 
       OR MVKE.AUMNG != MVKE4000.AUMNG
       OR MVKE.LFMNG != MVKE4000.LFMNG
       OR MVKE.SCMNG != MVKE4000.SCMNG
       OR MVKE.SCHME != MVKE4000.SCHME
       OR MVKE.RDPRF != MVKE4000.RDPRF
       OR MVKE.ZZMAXAU != MVKE4000.ZZMAXAU
       OR MVKE.ZZUOQ != MVKE4000.ZZUOQ
       OR MVKE.VERSG != MVKE4000.VERSG
       OR MVKE.KTGRM != MVKE4000.KTGRM
       OR (MVKE.MTPOS != MVKE4000.MTPOS AND (MVKE.VKORG != '4025' OR (MVKE.VKORG = '4025' AND MARA.MTPOS_MARA NOT LIKE 'ZRS%')))
       OR MVKE.PMATN != MVKE4000.PMATN
       OR MVKE.PROVG != MVKE4000.PROVG
       OR MVKE.MVGR1 != MVKE4000.MVGR1
       OR MVKE.MVGR2 != MVKE4000.MVGR2
       --OR MVKE.MVGR4 != MVKE4000.MVGR4
       --OR MVKE.PRAT1 != MVKE4000.PRAT1
       --OR MVKE.PRAT2 != MVKE4000.PRAT2
       OR MVKE.PRAT3 != MVKE4000.PRAT3
       OR MVKE.PRAT4 != MVKE4000.PRAT4
       --OR MVKE.PRAT5 != MVKE4000.PRAT5
       --OR MVKE.PRAT6 != MVKE4000.PRAT6
       OR MVKE.PRAT7 != MVKE4000.PRAT7
       OR MVKE.PRAT8 != MVKE4000.PRAT8
       OR MVKE.PRAT9 != MVKE4000.PRAT9       
       --OR MVKE.PRATA != MVKE4000.PRATA
       OR MVKE.ZZABSDT != MVKE4000.ZZABSDT
       OR MVKE.ZZPFRPD != MVKE4000.ZZPFRPD
       OR MVKE.ZZWEERG != MVKE4000.ZZWEERG
       OR MVKE.ZZSLRDT != MVKE4000.ZZSLRDT
       )
ORDER BY MVKE.VKORG, MVKE.MATNR